export const CHECK_PEER_STATUS_START = 'CHECK_PEER_STATUS_START';
export const CHECK_PEER_STATUS_SUCCESS = 'CHECK_PEER_STATUS_SUCCESS';
export const CHECK_PEER_STATUS_FAILURE = 'CHECK_PEER_STATUS_FAILURE';
